"""add-usenet-columns

Revision ID: 333866afcd2c
Revises: aa4689f80796
Create Date: 2025-07-09 20:55:42.338629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "333866afcd2c"
down_revision: Union[str, None] = "aa4689f80796"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usenet_download")
    op.add_column(
        "indexer_query_result",
        sa.Column(
            "usenet", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "indexer_query_result",
        sa.Column("age", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "torrent",
        sa.Column(
            "usenet", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("torrent", "usenet")
    op.drop_column("indexer_query_result", "age")
    op.drop_column("indexer_query_result", "usenet")
    op.create_table(
        "usenet_download",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "queued",
                "downloading",
                "completed",
                "failed",
                "paused",
                "extracting",
                "verifying",
                "repairing",
                "unknown",
                name="usenetdownloadstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "quality",
            postgresql.ENUM("uhd", "fullhd", "hd", "sd", "unknown", name="quality"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("imported", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("nzb_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "size_mb",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "progress_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("usenet_download_pkey")),
    )
    # ### end Alembic commands ###
